WIDTH = 500
HEIGHT = 800

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50  
PLAYER_SPEED = 5
PLAYER_IMAGE_PATH = "obrazky/player.png"

BLOCK_WIDTH = 50
BLOCK_HEIGHT = 50
BLOCK_IMAGE_PATH = "obrazky/asteroid.png"
BLOCK_SPEED = 5